### ISSUE TITLE
Error: cannot read property 'dir' of null

### ISSUE THREAD

**Issue by Pirol62** [maykar/lovelace-swipe-navigation#34]
I got this error only in two of four dashboards
Both are displays with only 1 view
Hassio Version 116.2
Swipe Navigation 1.2.5

**Comment by maykar** [comment]
Try latest release: 1.2.6

**Comment by Pirol62** [comment]
Did it.
The error now is: 
/swipe-navigation.js:45:38 Uncaught TypeError: Cannot read property 'querySelectorAll' of null
PS: I don't know if it is interesting or relevant: I use card_mod and the disable header mods, provided by yourself.

**Comment by maykar** [comment]
Going to need to go through the code and add exceptions for any dashboard that only uses one view. Don't have the time at the moment, but I'm on it. The card-mod additions shouldn't have any effect on this.

**Comment by Pirol62** [comment]
Take your time - that hasn't a priority higher then 150. :-)
Thank you

**Comment by maykar** [comment]
Should be fixed in the latest release 1.2.7

Give it a shot and close if that does it.

**Comment by maykar** [comment]
Fairly confident that this is fixed so going to close, but please let me know if you're still having issues.

**Comment by rickycraft** [comment]
I still have problems:

https://myhomeassistanturl:8123/local/community/lovelace-swipe-navigation/swipe-navigation.js:26:46 Uncaught TypeError: Cannot read property 'dir' of null

Homeassistant version: 0.117.5
Hassio: 2020.11.0
Version: 1.3.0

**Comment by rickycraft** [comment]
> I still have problems:
> 
> https://myhomeassistanturl:8123/local/community/lovelace-swipe-navigation/swipe-navigation.js:26:46 Uncaught TypeError: Cannot read property 'dir' of null
> 
> Homeassistant version: 0.117.5
> Hassio: 2020.11.0
> Version: 1.3.0

Turns out i had the old resource that was loading and not the new one installed from hacs
